name: Deploy to Zone
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://bizarrelabs.one
    steps:
      - name: Checkout to main
        uses: actions/checkout@main
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Clear any existing known_hosts entries and add the server key
          rm -f ~/.ssh/known_hosts
          echo "Scanning SSH host keys for ${{ secrets.HOST_SERVER_IP }}..."
          # Scan for all common key types (RSA, ECDSA, ED25519)
          ssh-keyscan -t rsa,ecdsa,ed25519 -H ${{ secrets.HOST_SERVER_IP }} >> ~/.ssh/known_hosts
          # Verify the keys were added successfully
          echo "Known hosts file contents:"
          cat ~/.ssh/known_hosts
      - name: Copy files to server
        run: |
          rsync -vrm --delete -e "ssh -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts" ./ ${{ secrets.SSH_LOGIN_CREDS }}:/data01/virt115405/domeenid/www.bizarrelabs.one/htdocs
